### PR TITLE
iconsadded

### PR DESCRIPTION
**Pull request by MujahidAli954**

### CODE REVIEW

**Comment by Sam-Varghese** [comment]
@MujahidAli954 Thanks for creating your first PR in TEDxNMIMSIndore.  It would be great if you could also do the following changes

1) Navigation bar I think needs more update as its view on mobile doesn't look perfect. 

image

I think we should put the icons, and text like About, Team, speakers, etc on a different line

2) Icons have not been added to the rest of the pages like _sponsors2022, sponsors2021, speakers2022, stc_

**Comment by MujahidAli954** [comment]
> @MujahidAli954 Thanks for creating your first PR in TEDxNMIMSIndore.
> 
> The icons have not been added to the rest of the pages like _sponsors2022, sponsors2021, speakers2022, stc_ Can you also update these webpages

I think you can use this as component that's why i cannot add

**Comment by MujahidAli954** [comment]
> @MujahidAli954 Thanks for creating your first PR in TEDxNMIMSIndore. It would be great if you could also do the following changes
> 
> 1. Navigation bar I think needs more update as its view on mobile doesn't look perfect.
> 
> image
> 
> I think we should put the icons, and text like About, Team, speakers, etc on a different line
> 
> 2. Icons have not been added to the rest of the pages like _sponsors2022, sponsors2021, speakers2022, stc_

ok I added and then make a pull request

**Comment by Sam-Varghese** [comment]
> > @MujahidAli954 Thanks for creating your first PR in TEDxNMIMSIndore.
> > The icons have not been added to the rest of the pages like _sponsors2022, sponsors2021, speakers2022, stc_ Can you also update these webpages
> 
> I think you can use this as component that's why i cannot add

Actually, there's only 1 component for displaying the navigation bar, but this component returns different output based on the props it's given. 

https://github.com/TEDx-NMIMS-Indore/TEDxNMIMSIndore-official-website/blob/ff1922f13005bd0173726dfc6f04b633e11a7315/src/components/menu/menu.js#L11

I can handle this trivial issue by myself, you can concentrate on the 2nd issue, ie. view of nav bar on mobile

**Comment by MujahidAli954** [comment]
> > > @MujahidAli954 Thanks for creating your first PR in TEDxNMIMSIndore.
> > > The icons have not been added to the rest of the pages like _sponsors2022, sponsors2021, speakers2022, stc_ Can you also update these webpages
> > 
> > 
> > I think you can use this as component that's why i cannot add
> 
> Actually, there's only 1 component for displaying the navigation bar, but this component returns different output based on the props it's given.
> 
> https://github.com/TEDx-NMIMS-Indore/TEDxNMIMSIndore-official-website/blob/ff1922f13005bd0173726dfc6f04b633e11a7315/src/components/menu/menu.js#L11
> 
> I can handle this trivial issue by myself, you can concentrate on the 2nd issue, ie. view of nav bar on mobile

ok I understand it now

**Comment by MujahidAli954** [comment]
I make it responsive
check this one
image

**Comment by Sam-Varghese** [comment]
Looks great!

**Comment by MujahidAli954** [comment]
I made a new pull request kindly check it

**Pull request merged**
